# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Project2'
    organization: 'team1-p2'
    scannerMode: 'MSBuild'
    projectKey: '83eb8a219dce6a51ed0afaaa0d9c5c55fad2f582'
    projectName: 'Team1 P2'
    extraProperties: |
      sonar.exclusions=**/obj/**,**/*.dll
      sonar.branch.name=$(Build.SourceBranchName)
      sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx
      sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/*.xml
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'
#run tests
- task: DotNetCoreCLI@2
  displayName: 'dotnet testing'
  inputs:
    command: 'test'
    arguments: '--configuration $(BuildConfiguration)
      /p:CollectCoverage=true 
      /p:CoverletOutputFormat=opencover 
      /p:Coverletoutput=$(Build.SourcesDirectory)/TestResults/Coverage 
      --collect "Codecoverage"
      --logger trx'
    projects: '**/*UnitTests.csproj'
    nobuild: true
- task: SonarCloudAnalyze@1
- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/**/*.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'